name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Hello world       # Name of step
      run: echo 'Hello world' # Command to run

    - name: Build App
      run: dotnet build
    
    - name: Install npm
      working-directory: DotnetTemplate.Web
      run: 
        npm install
        npm run build 
     
    - name: Run Tests
      run: dotnet test

    - name: Run linter and typscript tests
      working-directory: DotnetTemplate.Web
      run:
        npm t
        npm run lint

